/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { AdminApprovalControllerRejectVerification200OneOf } from './adminApprovalControllerRejectVerification200OneOf';
import type { AdminApprovalControllerRejectVerification200OneOfTwo } from './adminApprovalControllerRejectVerification200OneOfTwo';

export type AdminApprovalControllerRejectVerification200 = AdminApprovalControllerRejectVerification200OneOf | AdminApprovalControllerRejectVerification200OneOfTwo;
