/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { Company } from './company';
import type { AdminApprovalControllerGetPendingVerifications200AllOfMetadata } from './adminApprovalControllerGetPendingVerifications200AllOfMetadata';

export type AdminApprovalControllerGetPendingVerifications200AllOf = {
  data?: Company[];
  metadata?: AdminApprovalControllerGetPendingVerifications200AllOfMetadata;
};
