/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { BlogControllerCreate200OneOf } from './blogControllerCreate200OneOf';
import type { BlogControllerCreate200OneOfTwo } from './blogControllerCreate200OneOfTwo';

export type BlogControllerCreate200 = BlogControllerCreate200OneOf | BlogControllerCreate200OneOfTwo;
