/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CategoryResponseDto } from './categoryResponseDto';
import type { CategoryControllerFindAll200AllOfMetadata } from './categoryControllerFindAll200AllOfMetadata';

export type CategoryControllerFindAll200AllOf = {
  data?: CategoryResponseDto[];
  metadata?: CategoryControllerFindAll200AllOfMetadata;
};
