/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type CategoryControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * 페이지 크기, max 1000
 */
limit?: number;
/**
 * 코드 타입
 */
cdClsfNm?: string;
/**
 * 숫자 코드
 */
cd?: string;
/**
 * 코드 이름
 */
cdNm?: string;
/**
 * 코드 레벨 검색
 */
cdLvl?: number;
};
