/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CategoryControllerCreate200OneOf } from './categoryControllerCreate200OneOf';
import type { CategoryControllerCreate200OneOfTwo } from './categoryControllerCreate200OneOfTwo';

export type CategoryControllerCreate200 = CategoryControllerCreate200OneOf | CategoryControllerCreate200OneOfTwo;
