/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 채널 제안 상태, 01: 대기, 02: 승인, 03: 취소
 */
export type ChannelProposalControllerUpdateStatusBodyStatus = typeof ChannelProposalControllerUpdateStatusBodyStatus[keyof typeof ChannelProposalControllerUpdateStatusBodyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelProposalControllerUpdateStatusBodyStatus = {
  NUMBER_01: '01',
  NUMBER_02: '02',
  NUMBER_03: '03',
} as const;
