/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ChannelProposalControllerUpdate200OneOf } from './channelProposalControllerUpdate200OneOf';
import type { ChannelProposalControllerUpdate200OneOfTwo } from './channelProposalControllerUpdate200OneOfTwo';

export type ChannelProposalControllerUpdate200 = ChannelProposalControllerUpdate200OneOf | ChannelProposalControllerUpdate200OneOfTwo;
