/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ChannelProposalControllerUpdateStatus200OneOf } from './channelProposalControllerUpdateStatus200OneOf';
import type { ChannelProposalControllerUpdateStatus200OneOfTwo } from './channelProposalControllerUpdateStatus200OneOfTwo';

export type ChannelProposalControllerUpdateStatus200 = ChannelProposalControllerUpdateStatus200OneOf | ChannelProposalControllerUpdateStatus200OneOfTwo;
