/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type ChannelProposalControllerUpdateStatus200OneOfTwo = {
  data?: null;
};
