/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ChannelProposalResponseDto } from './channelProposalResponseDto';
import type { ChannelProposalControllerFindAll200AllOfMetadata } from './channelProposalControllerFindAll200AllOfMetadata';

export type ChannelProposalControllerFindAll200AllOf = {
  data?: ChannelProposalResponseDto[];
  metadata?: ChannelProposalControllerFindAll200AllOfMetadata;
};
