/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ChannelProposalControllerFindAllAplyStts } from './channelProposalControllerFindAllAplyStts';

export type ChannelProposalControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * 채널명으로 검색
 */
chnNm?: string;
/**
 * 신청 상태로 필터링 01: 대기, 02: 승인, 03: 취소
 */
aplyStts?: ChannelProposalControllerFindAllAplyStts;
};
