/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ChannelProposalControllerUpdateStatusBodyStatus } from './channelProposalControllerUpdateStatusBodyStatus';

export type ChannelProposalControllerUpdateStatusBody = {
  proposalIds?: number[];
  /** 채널 제안 상태, 01: 대기, 02: 승인, 03: 취소 */
  status?: ChannelProposalControllerUpdateStatusBodyStatus;
};
