/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type ChannelProposalControllerFindAllAplyStts = typeof ChannelProposalControllerFindAllAplyStts[keyof typeof ChannelProposalControllerFindAllAplyStts];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelProposalControllerFindAllAplyStts = {
  NUMBER_01: '01',
  NUMBER_02: '02',
  NUMBER_03: '03',
} as const;
