/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ChannelProposalControllerCreate200OneOf } from './channelProposalControllerCreate200OneOf';
import type { ChannelProposalControllerCreate200OneOfTwo } from './channelProposalControllerCreate200OneOfTwo';

export type ChannelProposalControllerCreate200 = ChannelProposalControllerCreate200OneOf | ChannelProposalControllerCreate200OneOfTwo;
