/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 신청 상태
 */
export type ChannelProposalResponseDtoAplyStts = typeof ChannelProposalResponseDtoAplyStts[keyof typeof ChannelProposalResponseDtoAplyStts];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelProposalResponseDtoAplyStts = {
  NUMBER_01: '01',
  NUMBER_02: '02',
  NUMBER_03: '03',
} as const;
