/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CompaniesControllerCreate200OneOf } from './companiesControllerCreate200OneOf';
import type { CompaniesControllerCreate200OneOfTwo } from './companiesControllerCreate200OneOfTwo';

export type CompaniesControllerCreate200 = CompaniesControllerCreate200OneOf | CompaniesControllerCreate200OneOfTwo;
