/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ResponseCompanyDto } from './responseCompanyDto';
import type { CompaniesControllerFindAll200AllOfMetadata } from './companiesControllerFindAll200AllOfMetadata';

export type CompaniesControllerFindAll200AllOf = {
  data?: ResponseCompanyDto[];
  metadata?: CompaniesControllerFindAll200AllOfMetadata;
};
