/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CompaniesControllerFindOne200OneOf } from './companiesControllerFindOne200OneOf';
import type { CompaniesControllerFindOne200OneOfTwo } from './companiesControllerFindOne200OneOfTwo';

export type CompaniesControllerFindOne200 = CompaniesControllerFindOne200OneOf | CompaniesControllerFindOne200OneOfTwo;
