/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CompaniesControllerRemove200OneOf } from './companiesControllerRemove200OneOf';
import type { CompaniesControllerRemove200OneOfTwo } from './companiesControllerRemove200OneOfTwo';

export type CompaniesControllerRemove200 = CompaniesControllerRemove200OneOf | CompaniesControllerRemove200OneOfTwo;
