/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CompaniesControllerUpdate200OneOf } from './companiesControllerUpdate200OneOf';
import type { CompaniesControllerUpdate200OneOfTwo } from './companiesControllerUpdate200OneOfTwo';

export type CompaniesControllerUpdate200 = CompaniesControllerUpdate200OneOf | CompaniesControllerUpdate200OneOfTwo;
