/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CompaniesControllerFindOneByUser200OneOf } from './companiesControllerFindOneByUser200OneOf';
import type { CompaniesControllerFindOneByUser200OneOfTwo } from './companiesControllerFindOneByUser200OneOfTwo';

export type CompaniesControllerFindOneByUser200 = CompaniesControllerFindOneByUser200OneOf | CompaniesControllerFindOneByUser200OneOfTwo;
