/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CompaniesControllerFindAllCertStatus } from './companiesControllerFindAllCertStatus';

export type CompaniesControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * Search by company name
 */
companyName?: string;
/**
 * Search by company registration number
 */
companyNumber?: string;
/**
 * Search by boss name
 */
bossName?: string;
/**
 * Search by email
 */
email?: string;
/**
 * Search by company cert status 
 01: UNCERTIFIED 
 02: APPROVED 
 03: PENDING 
 04: REJECTED
 */
certStatus?: CompaniesControllerFindAllCertStatus;
};
