/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface CreateProposalDocumentReviewDto {
  /** 신청 내용 */
  aplyCn: string;
  /** 신청 제목 */
  aplyTtl: string;
  /** 회사명 */
  coNm: string;
  /** 이메일 */
  picEmail: string;
  /** 담당자명 */
  picNm: string;
  /** 전화번호 */
  picTelno: string;
  /** 프로젝트 문서 번호 */
  prpslDocPageNo: number;
  /** 유저 ID */
  userId: number;
}
