/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CreateProductSourcingDtoAplyCn } from './createProductSourcingDtoAplyCn';

export interface CreateProductSourcingDto {
  /** 신청내용 */
  aplyCn?: CreateProductSourcingDtoAplyCn;
  /** 의뢰신청명 */
  aplymNm: string;
  /** 상품 분류값 */
  prdctClsfVl: string;
}
