/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface CreateProposalInfoDto {
  /** 제안 채널 이름 */
  prpslChnNm: string;
  /** 제안 문서 색상 */
  prpslColorNm: string;
  /** 제안문서 내용 (JSON 값) */
  prpslDocCn: string;
  /** 제안 문서 작성일 */
  prpslDocWrtYmd: string;
  /** 제안 문서 폰트 */
  prpslFontNm: string;
}
