/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 연관된 엔티티 타입, blog, question, company, product ...
 */
export type CreateMediaFileDtoEntityType = typeof CreateMediaFileDtoEntityType[keyof typeof CreateMediaFileDtoEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMediaFileDtoEntityType = {
  blog: 'blog',
  question: 'question',
  company: 'company',
  product: 'product',
  proposal: 'proposal',
  proposal_sample: 'proposal_sample',
} as const;
