/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CreatePaymentInfoDtoStlmSttsCd } from './createPaymentInfoDtoStlmSttsCd';

export interface CreatePaymentInfoDto {
  /** 승인오류코드 */
  aprvErrCd?: string;
  /** 승인번호 */
  aprvNo?: string;
  /** 결제상태 */
  billingKey?: string;
  /** 카드사명 */
  cardCoNm?: string;
  /** 입금은행명 */
  dpstBankNm?: string;
  /** 결제자명 */
  pyrNm?: string;
  /** 결제금액 */
  stlmAmt?: number;
  /** 결제ID */
  stlmId: string;
  /** 결제수단 */
  stlmMthdVl?: string;
  /** 결제상태 */
  stlmSttsCd: CreatePaymentInfoDtoStlmSttsCd;
}
