/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface CreateCompanyDto {
  /** 대표 성함 */
  bossName: string;
  /** 회사 사업자 등록증  경로 */
  brCertFilePathVl?: string;
  /**
   * 회사 주소
   * @nullable
   */
  coAddr?: string | null;
  /** 회사 설명 */
  coDescCn?: string;
  /** 회사 이미지 경로 */
  coImgPathVl?: string;
  /** 회사 이름 */
  companyName: string;
  /** 사업자 등록 번호 */
  companyNumber: string;
  /** 회사 전화번호 */
  coTelno?: string;
  /** 담당자 이메일 */
  picEmail: string;
  /** 담당자 성 */
  picFlNm: string;
  /** 담당자 이름 */
  picNm: string;
  /** 담당자 전화번호 */
  picTelno: string;
}
