/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 문의유형(01: 1대1문의, 02: 서비스 문의)
 */
export type CreateQuestionAnswerDtoQstnTypeCd = typeof CreateQuestionAnswerDtoQstnTypeCd[keyof typeof CreateQuestionAnswerDtoQstnTypeCd];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionAnswerDtoQstnTypeCd = {
  NUMBER_01: '01',
  NUMBER_02: '02',
} as const;
