/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface CreateEduFormDto {
  /** 교육 ID */
  educationId: number;
  /**
   * 이메일
   * @maxLength 200
   */
  email: string;
  /** 마케팅 수신 동의 여부 */
  marketingChecked: boolean;
  /**
   * 이름
   * @maxLength 100
   */
  name: string;
  /**
   * 전화번호
   * @maxLength 200
   */
  phone: string;
}
