/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CreateMediaFileDtoEntityType } from './createMediaFileDtoEntityType';

export interface CreateMediaFileDto {
  /** 연관된 엔티티 ID */
  entityId?: number;
  /** 연관된 엔티티 타입, blog, question, company, product ... */
  entityType: CreateMediaFileDtoEntityType;
  /** 파일 이름 */
  fileName: string;
  /** 파일의 MIME 타입 */
  mimeType: string;
  /**
   * 파일 크기 (바이트)
   * @minimum 1
   */
  size: number;
  /** 사용자 ID */
  userId?: number;
}
