/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface CreateCategoryDto {
  /** 코드 번호 (string) */
  cd: string;
  /** 코드 유형 (category | mtag) */
  cdClsfNm: string;
  /** 코드 레벨 검색 1, 2, 3, 4 */
  cdLvl: number;
  /** 코드 문자 */
  cdNm: string;
  /**
   * 코드 전체명 for cdLvl4 category
   * @maxLength 200
   */
  cdWholNm?: string;
}
