/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 결제상태
 */
export type CreatePaymentInfoDtoStlmSttsCd = typeof CreatePaymentInfoDtoStlmSttsCd[keyof typeof CreatePaymentInfoDtoStlmSttsCd];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePaymentInfoDtoStlmSttsCd = {
  paid: 'paid',
  cancelled: 'cancelled',
} as const;
