/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface CreateProposalSampleDto {
  /**
   * 페이지번호
   * @maxLength 100
   */
  page: string;
  /**
   * 샘플파일경로
   * @maxLength 100
   */
  smplFilePathVl: string;
  /**
   * 제목
   * @maxLength 100
   */
  ttl: string;
}
