/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface CreateSubscriptionDto {
  /**
   * 결제자이메일
   * @maxLength 100
   */
  pyrEml?: string;
  /**
   * 결제자휴대폰번호
   * @maxLength 20
   */
  pyrMblTelno?: string;
  /**
   * 결제자명
   * @maxLength 20
   */
  pyrNm: string;
  /** 구독시작일 */
  sbscrbBgngYmd: string;
  /** 구독종료일 */
  sbscrbEndYmd: string;
  /**
   * 구독구분코드 일반:01, 정기:02
   * @maxLength 2
   */
  sbscrbSeCd: string;
  /**
   * 결제ID
   * @maxLength 50
   */
  stlmId: string;
  /**
   * 구독구분코드 BASIC:01, MASTER:02
   * @maxLength 2
   */
  userSeCd: string;
}
