/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface CreateEduLinkDto {
  /** 카테고리 ID, 1: 화장품, 2: youtube, 3: 음식, 5: 컨설팅 */
  categoryId: number;
  /** 인스타그램 정보 */
  instagram?: string;
  /**
   * URL
   * @maxLength 200
   */
  url: string;
}
