/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface CreateProductDto {
  /** 추가 이미지1 경로 */
  addImgPath1Vl?: string;
  /** 추가 이미지2 경로 */
  addImgPath2Vl?: string;
  /** 브랜드명 */
  brandNm: string;
  /** 용기형태 */
  bttlShp?: string;
  /** 구성 */
  cmpsVl?: string;
  /** 중량 */
  cpctVl?: string;
  /** 카테고리  */
  ctgrCd: string;
  /** 삭제 여부 */
  delYn?: string;
  /** 소개 자료 첨부 */
  explnAtchFilePathVl?: string;
  /** 입수 */
  getVl?: string;
  /** 입수 수량 */
  inRcvQntVl?: string;
  /** 인허가인증파일 */
  lcpmtCertFilePathVl?: string;
  /** 주요 효능 */
  mainEffcncVl?: string;
  /** 주요 성분 */
  mainIgdVl?: string;
  /** 제조국 */
  mnftrNtnNm?: string;
  /** 상품 금액 */
  prdctAmt?: string;
  /** 상품 설명 */
  prdctCn?: string;
  /** 상품 정보 내용 */
  prdctInfoCn?: string;
  /** 상품명 */
  prdctNm: string;
  /** 상품 판매 채널 */
  prdctNtslChnVl?: string;
  /** 제품 규격 */
  prdctSpcfctVl?: string;
  /** 제안가 */
  prpslAmt?: string;
  /** 제안서 페이지 번호 */
  prpslDocPageNo?: number;
  /** 권유 고객 */
  rcmdtnCustNm?: string;
  /** 권유 포인트 */
  rcmdtnPntCn?: string;
  /** 수신 수량 */
  rcvQntVl?: string;
  /** 출고 일시 */
  rlsDt?: string;
  /** 유통기한 */
  rtlTermYmd: string;
  /** 태그 */
  tagCd?: string;
  /** 썸네일 누끼 이미지 경로 */
  thumbImgPath2Vl: string;
  /** 썸네일 이미지 경로 */
  thumbImgPathVl: string;
  /** 사용 방법 내용 */
  useMthdCn?: string;
}
