/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CreateQuestionAnswerDtoQstnTypeCd } from './createQuestionAnswerDtoQstnTypeCd';

export interface CreateQuestionAnswerDto {
  /** 첨부파일경로 */
  attchFilePathVl?: string;
  /** 희망 유통 채널명 */
  chnNm?: string;
  /** 문의 답변 */
  cn: string;
  /** 회사명 */
  coNm?: string;
  /** 이메일 */
  picEmail: string;
  /** 이름 */
  picNm: string;
  /** 전화번호 */
  picTelno: string;
  /** 문의유형(01: 1대1문의, 02: 서비스 문의) */
  qstnTypeCd: CreateQuestionAnswerDtoQstnTypeCd;
  /** 문의 내용 */
  ttl: string;
  /** 상위 ID */
  upId?: number;
  /**
   * 사용자 ID
   * @nullable
   */
  userId?: number | null;
}
