/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoRole } from './createUserDtoRole';

export interface CreateUserDto {
  /** User email address */
  email: string;
  /** User password */
  password: string;
  /** 01: MERCHANT, 02: BUSINESS, 09: ADMIN */
  role: CreateUserDtoRole;
}
