/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type EducationControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * 교육 제목 검색
 */
title?: string;
/**
 * 관리자 선택 여부 필터링
 */
isAdminPick?: boolean;
};
