/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface EducationCategory {
  /**
   * 카테고리 이름
   * @nullable
   */
  category: string | null;
  /** 카테고리 ID */
  id: number;
  /**
   * 교육 여부
   * @nullable
   */
  isEdu: boolean | null;
  /**
   * 상품 여부
   * @nullable
   */
  isProduct: boolean | null;
}
