/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { EducationControllerFindOne200OneOf } from './educationControllerFindOne200OneOf';
import type { EducationControllerFindOne200OneOfTwo } from './educationControllerFindOne200OneOfTwo';

export type EducationControllerFindOne200 = EducationControllerFindOne200OneOf | EducationControllerFindOne200OneOfTwo;
