/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { EducationControllerUpdate200OneOf } from './educationControllerUpdate200OneOf';
import type { EducationControllerUpdate200OneOfTwo } from './educationControllerUpdate200OneOfTwo';

export type EducationControllerUpdate200 = EducationControllerUpdate200OneOf | EducationControllerUpdate200OneOfTwo;
