/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { Education } from './education';
import type { EducationControllerFindAll200AllOfMetadata } from './educationControllerFindAll200AllOfMetadata';

export type EducationControllerFindAll200AllOf = {
  data?: Education[];
  metadata?: EducationControllerFindAll200AllOfMetadata;
};
