/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { EducationControllerCreate200OneOf } from './educationControllerCreate200OneOf';
import type { EducationControllerCreate200OneOfTwo } from './educationControllerCreate200OneOfTwo';

export type EducationControllerCreate200 = EducationControllerCreate200OneOf | EducationControllerCreate200OneOfTwo;
