/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface Education {
  /** 생성일 */
  createdAt: string;
  /** 종료일 */
  endDate: string;
  /** 교육 ID */
  id: number;
  /**
   * 이미지
   * @nullable
   */
  image: string | null;
  /** 관리자 선택 여부 */
  isAdminPick: boolean;
  /**
   * 장소
   * @nullable
   */
  place: string | null;
  /** 가격 */
  price: number;
  /** 시작일 */
  startDate: string;
  /**
   * 대상
   * @nullable
   */
  target: string | null;
  /** 제목 */
  title: string;
}
