/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { Education } from './education';

export interface EduForm {
  /** 생성일 */
  createdAt: string;
  /** 교육 정보 */
  education: Education;
  /**
   * 이메일
   * @nullable
   */
  email: string | null;
  /** 교육 신청 ID */
  id: number;
  /**
   * 마케팅 동의 여부
   * @nullable
   */
  marketingChecked: boolean | null;
  /** 이름 */
  name: string;
  /**
   * 전화번호
   * @nullable
   */
  phone: string | null;
}
