/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { EduFormControllerCreate200OneOf } from './eduFormControllerCreate200OneOf';
import type { EduFormControllerCreate200OneOfTwo } from './eduFormControllerCreate200OneOfTwo';

export type EduFormControllerCreate200 = EduFormControllerCreate200OneOf | EduFormControllerCreate200OneOfTwo;
