/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { EduForm } from './eduForm';
import type { EduFormControllerFindAll200AllOfMetadata } from './eduFormControllerFindAll200AllOfMetadata';

export type EduFormControllerFindAll200AllOf = {
  data?: EduForm[];
  metadata?: EduFormControllerFindAll200AllOfMetadata;
};
