/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type EduFormControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * 이름 검색
 */
name?: string;
/**
 * 이메일 검색
 */
email?: string;
/**
 * 전화번호 검색
 */
phone?: string;
/**
 * 교육 ID로 필터링
 */
educationId?: number;
};
