/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { EducationCategory } from './educationCategory';

export interface EduLink {
  /** 카테고리 정보 */
  category: EducationCategory;
  /** 생성일 */
  createdAt: string;
  /** 교육 링크 ID */
  id: number;
  /**
   * 인스타그램
   * @nullable
   */
  instagram: string | null;
  /**
   * URL
   * @nullable
   */
  url: string | null;
}
