/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { EduLinkControllerCreate200OneOf } from './eduLinkControllerCreate200OneOf';
import type { EduLinkControllerCreate200OneOfTwo } from './eduLinkControllerCreate200OneOfTwo';

export type EduLinkControllerCreate200 = EduLinkControllerCreate200OneOf | EduLinkControllerCreate200OneOfTwo;
