/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { EduLink } from './eduLink';
import type { EduLinkControllerFindAll200AllOfMetadata } from './eduLinkControllerFindAll200AllOfMetadata';

export type EduLinkControllerFindAll200AllOf = {
  data?: EduLink[];
  metadata?: EduLinkControllerFindAll200AllOfMetadata;
};
