/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type EduLinkControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * URL 검색
 */
url?: string;
/**
 * 인스타그램 검색
 */
instagram?: string;
/**
 * 카테고리 ID로 필터링
 */
categoryId?: number;
};
