/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { EmailVerificationControllerVerifyCode200Status } from './emailVerificationControllerVerifyCode200Status';

export type EmailVerificationControllerVerifyCode200 = {
  status?: EmailVerificationControllerVerifyCode200Status;
};
