/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type EmailVerificationControllerVerifyCode200Status = typeof EmailVerificationControllerVerifyCode200Status[keyof typeof EmailVerificationControllerVerifyCode200Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmailVerificationControllerVerifyCode200Status = {
  verified: 'verified',
  expired: 'expired',
  invalid: 'invalid',
} as const;
