/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type EmailVerificationControllerSendVerificationEmail200Status = typeof EmailVerificationControllerSendVerificationEmail200Status[keyof typeof EmailVerificationControllerSendVerificationEmail200Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmailVerificationControllerSendVerificationEmail200Status = {
  success: 'success',
  duplicated: 'duplicated',
} as const;
