/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { MediaFileControllerInitializeUpload200OneOf } from './mediaFileControllerInitializeUpload200OneOf';
import type { MediaFileControllerInitializeUpload200OneOfTwo } from './mediaFileControllerInitializeUpload200OneOfTwo';

export type MediaFileControllerInitializeUpload200 = MediaFileControllerInitializeUpload200OneOf | MediaFileControllerInitializeUpload200OneOfTwo;
