/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { PaymentInfoResponseDto } from './paymentInfoResponseDto';
import type { PaymentInfoControllerFindAll200AllOfMetadata } from './paymentInfoControllerFindAll200AllOfMetadata';

export type PaymentInfoControllerFindAll200AllOf = {
  data?: PaymentInfoResponseDto[];
  metadata?: PaymentInfoControllerFindAll200AllOfMetadata;
};
