/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { PaymentInfoControllerFindOne200OneOf } from './paymentInfoControllerFindOne200OneOf';
import type { PaymentInfoControllerFindOne200OneOfTwo } from './paymentInfoControllerFindOne200OneOfTwo';

export type PaymentInfoControllerFindOne200 = PaymentInfoControllerFindOne200OneOf | PaymentInfoControllerFindOne200OneOfTwo;
