/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type PaymentInfoControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * 결제 ID
 */
stlmId?: string;
/**
 * 사용자 ID
 */
userId?: number;
/**
 * 결제 상태 코드
 */
stlmSttsCd?: string;
};
