/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { PaymentInfoControllerCancel200OneOf } from './paymentInfoControllerCancel200OneOf';
import type { PaymentInfoControllerCancel200OneOfTwo } from './paymentInfoControllerCancel200OneOfTwo';

export type PaymentInfoControllerCancel200 = PaymentInfoControllerCancel200OneOf | PaymentInfoControllerCancel200OneOfTwo;
