/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { PaymentInfoResponseDtoAprvErrCd } from './paymentInfoResponseDtoAprvErrCd';
import type { PaymentInfoResponseDtoAprvNo } from './paymentInfoResponseDtoAprvNo';
import type { PaymentInfoResponseDtoCardCoNm } from './paymentInfoResponseDtoCardCoNm';
import type { PaymentInfoResponseDtoDpstBankNm } from './paymentInfoResponseDtoDpstBankNm';
import type { PaymentInfoResponseDtoMdfcnDt } from './paymentInfoResponseDtoMdfcnDt';
import type { PaymentInfoResponseDtoMdfrId } from './paymentInfoResponseDtoMdfrId';
import type { PaymentInfoResponseDtoPyrNm } from './paymentInfoResponseDtoPyrNm';
import type { PaymentInfoResponseDtoRegDt } from './paymentInfoResponseDtoRegDt';
import type { PaymentInfoResponseDtoRgtrId } from './paymentInfoResponseDtoRgtrId';
import type { PaymentInfoResponseDtoRgtrIp } from './paymentInfoResponseDtoRgtrIp';
import type { PaymentInfoResponseDtoRtrcnDt } from './paymentInfoResponseDtoRtrcnDt';
import type { PaymentInfoResponseDtoRtrcnRsnCn } from './paymentInfoResponseDtoRtrcnRsnCn';
import type { PaymentInfoResponseDtoStlmAmt } from './paymentInfoResponseDtoStlmAmt';
import type { PaymentInfoResponseDtoStlmMthdVl } from './paymentInfoResponseDtoStlmMthdVl';
import type { PaymentInfoResponseDtoStlmSttsCd } from './paymentInfoResponseDtoStlmSttsCd';
import type { UserResponseDto } from './userResponseDto';

export interface PaymentInfoResponseDto {
  /**
   * 승인오류코드
   * @nullable
   */
  aprvErrCd: PaymentInfoResponseDtoAprvErrCd;
  /**
   * 승인번호
   * @nullable
   */
  aprvNo: PaymentInfoResponseDtoAprvNo;
  /**
   * 카드사명
   * @nullable
   */
  cardCoNm: PaymentInfoResponseDtoCardCoNm;
  /**
   * 입금은행명
   * @nullable
   */
  dpstBankNm: PaymentInfoResponseDtoDpstBankNm;
  /**
   * 수정일시
   * @nullable
   */
  mdfcnDt: PaymentInfoResponseDtoMdfcnDt;
  /**
   * 수정자ID
   * @nullable
   */
  mdfrId: PaymentInfoResponseDtoMdfrId;
  /**
   * 결제자명
   * @nullable
   */
  pyrNm: PaymentInfoResponseDtoPyrNm;
  /**
   * 등록일시
   * @nullable
   */
  regDt: PaymentInfoResponseDtoRegDt;
  /**
   * 등록자ID
   * @nullable
   */
  rgtrId: PaymentInfoResponseDtoRgtrId;
  /**
   * 등록자IP
   * @nullable
   */
  rgtrIp: PaymentInfoResponseDtoRgtrIp;
  /**
   * 환불일시
   * @nullable
   */
  rtrcnDt: PaymentInfoResponseDtoRtrcnDt;
  /**
   * 환불사유
   * @nullable
   */
  rtrcnRsnCn: PaymentInfoResponseDtoRtrcnRsnCn;
  /**
   * 결제금액
   * @nullable
   */
  stlmAmt: PaymentInfoResponseDtoStlmAmt;
  /** 결제일시 */
  stlmDt: string;
  /** 결제ID */
  stlmId: string;
  /**
   * 결제수단
   * @nullable
   */
  stlmMthdVl: PaymentInfoResponseDtoStlmMthdVl;
  /**
   * 결제상태
   * @nullable
   */
  stlmSttsCd: PaymentInfoResponseDtoStlmSttsCd;
  /** 사용자 */
  user: UserResponseDto;
}
