/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { PaymentInfoControllerCreate200OneOf } from './paymentInfoControllerCreate200OneOf';
import type { PaymentInfoControllerCreate200OneOfTwo } from './paymentInfoControllerCreate200OneOfTwo';

export type PaymentInfoControllerCreate200 = PaymentInfoControllerCreate200OneOf | PaymentInfoControllerCreate200OneOfTwo;
