/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 등록자IP
 * @nullable
 */
export type PaymentInfoResponseDtoRgtrIp = { [key: string]: unknown } | null;
