/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 결제상태
 * @nullable
 */
export type PaymentInfoResponseDtoStlmSttsCd = { [key: string]: unknown } | null;
