/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type ProductsControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * 상품명으로 검색
 */
prdctNm?: string;
/**
 * 브랜드명(회사명)으로 검색
 */
brandNm?: string;
/**
 * 카테고리 코드로 검색
 */
ctgrCd?: string;
};
