/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type ProductSourcingMatchControllerFindMyMatchedProductsParams = {
/**
 * 페이지 번호 (기본값: 1)
 */
page?: number;
/**
 * 페이지 당 항목 수 (기본값: 10)
 */
limit?: number;
/**
 * 특정 소싱 ID로 필터링 (선택 사항)
 */
sourcingId?: number;
};
