/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProductResponseDto } from './productResponseDto';
import type { ProductSourcingMatchControllerFindMyMatchedProducts200AllOfMetadata } from './productSourcingMatchControllerFindMyMatchedProducts200AllOfMetadata';

export type ProductSourcingMatchControllerFindMyMatchedProducts200AllOf = {
  data?: ProductResponseDto[];
  metadata?: ProductSourcingMatchControllerFindMyMatchedProducts200AllOfMetadata;
};
