/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProductsControllerFindOne200OneOf } from './productsControllerFindOne200OneOf';
import type { ProductsControllerFindOne200OneOfTwo } from './productsControllerFindOne200OneOfTwo';

export type ProductsControllerFindOne200 = ProductsControllerFindOne200OneOf | ProductsControllerFindOne200OneOfTwo;
