/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDto } from './userResponseDto';

/**
 * 사용자 정보
 * @nullable
 */
export type ProductResponseDtoUser = UserResponseDto | null;
