/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProductsControllerUpdate200OneOf } from './productsControllerUpdate200OneOf';
import type { ProductsControllerUpdate200OneOfTwo } from './productsControllerUpdate200OneOfTwo';

export type ProductsControllerUpdate200 = ProductsControllerUpdate200OneOf | ProductsControllerUpdate200OneOfTwo;
