/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProductsControllerCreate200OneOf } from './productsControllerCreate200OneOf';
import type { ProductsControllerCreate200OneOfTwo } from './productsControllerCreate200OneOfTwo';

export type ProductsControllerCreate200 = ProductsControllerCreate200OneOf | ProductsControllerCreate200OneOfTwo;
