/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalDocumentReviewResponseDto } from './proposalDocumentReviewResponseDto';
import type { ProposalDocumentReviewControllerFindAll200AllOfMetadata } from './proposalDocumentReviewControllerFindAll200AllOfMetadata';

export type ProposalDocumentReviewControllerFindAll200AllOf = {
  data?: ProposalDocumentReviewResponseDto[];
  metadata?: ProposalDocumentReviewControllerFindAll200AllOfMetadata;
};
