/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalDocumentReviewResponseDtoAnsCn } from './proposalDocumentReviewResponseDtoAnsCn';
import type { ProposalDocumentReviewResponseDtoAnsDt } from './proposalDocumentReviewResponseDtoAnsDt';
import type { ProposalDocumentReviewResponseDtoAnsYn } from './proposalDocumentReviewResponseDtoAnsYn';
import type { ProposalDocumentReviewResponseDtoMdfcnDt } from './proposalDocumentReviewResponseDtoMdfcnDt';
import type { ProposalDocumentReviewResponseDtoMdfrId } from './proposalDocumentReviewResponseDtoMdfrId';

export interface ProposalDocumentReviewResponseDto {
  /**
   * 답변내용
   * @nullable
   */
  ansCn?: ProposalDocumentReviewResponseDtoAnsCn;
  /**
   * 답변일시
   * @nullable
   */
  ansDt?: ProposalDocumentReviewResponseDtoAnsDt;
  /**
   * 답변여부
   * @nullable
   */
  ansYn?: ProposalDocumentReviewResponseDtoAnsYn;
  /** 신청 내용 */
  aplyCn: string;
  /** 신청 제목 */
  aplyTtl: string;
  /** 회사명 */
  coNm: string;
  /** ID */
  id: number;
  /**
   * 수정 일시
   * @nullable
   */
  mdfcnDt?: ProposalDocumentReviewResponseDtoMdfcnDt;
  /**
   * 수정자 ID
   * @nullable
   */
  mdfrId?: ProposalDocumentReviewResponseDtoMdfrId;
  /** 이메일 */
  picEmail: string;
  /** 담당자명 */
  picNm: string;
  /** 전화번호 */
  picTelno: string;
  /** 프로젝트 문서 번호 */
  prpslDocPageNo: number;
  /** 등록 일시 */
  regDt: string;
  /** 등록자 ID */
  rgtrId: number;
  /** 유저 ID */
  userId: number;
}
