/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalLogResponseDto } from './proposalLogResponseDto';
import type { ProposalLogControllerFindAll200AllOfMetadata } from './proposalLogControllerFindAll200AllOfMetadata';

export type ProposalLogControllerFindAll200AllOf = {
  data?: ProposalLogResponseDto[];
  metadata?: ProposalLogControllerFindAll200AllOfMetadata;
};
