/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalInfoControllerUpdate200OneOf } from './proposalInfoControllerUpdate200OneOf';
import type { ProposalInfoControllerUpdate200OneOfTwo } from './proposalInfoControllerUpdate200OneOfTwo';

export type ProposalInfoControllerUpdate200 = ProposalInfoControllerUpdate200OneOf | ProposalInfoControllerUpdate200OneOfTwo;
