/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalLogControllerFindOne200OneOf } from './proposalLogControllerFindOne200OneOf';
import type { ProposalLogControllerFindOne200OneOfTwo } from './proposalLogControllerFindOne200OneOfTwo';

export type ProposalLogControllerFindOne200 = ProposalLogControllerFindOne200OneOf | ProposalLogControllerFindOne200OneOfTwo;
