/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type ProposalDocumentReviewControllerFindAllAnsYn = typeof ProposalDocumentReviewControllerFindAllAnsYn[keyof typeof ProposalDocumentReviewControllerFindAllAnsYn];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalDocumentReviewControllerFindAllAnsYn = {
  Y: 'Y',
  N: 'N',
} as const;
