/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalSampleControllerCreate200OneOf } from './proposalSampleControllerCreate200OneOf';
import type { ProposalSampleControllerCreate200OneOfTwo } from './proposalSampleControllerCreate200OneOfTwo';

export type ProposalSampleControllerCreate200 = ProposalSampleControllerCreate200OneOf | ProposalSampleControllerCreate200OneOfTwo;
