/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalInfoControllerFindOne200OneOf } from './proposalInfoControllerFindOne200OneOf';
import type { ProposalInfoControllerFindOne200OneOfTwo } from './proposalInfoControllerFindOne200OneOfTwo';

export type ProposalInfoControllerFindOne200 = ProposalInfoControllerFindOne200OneOf | ProposalInfoControllerFindOne200OneOfTwo;
