/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalDocumentReviewControllerFindOne200OneOf } from './proposalDocumentReviewControllerFindOne200OneOf';
import type { ProposalDocumentReviewControllerFindOne200OneOfTwo } from './proposalDocumentReviewControllerFindOne200OneOfTwo';

export type ProposalDocumentReviewControllerFindOne200 = ProposalDocumentReviewControllerFindOne200OneOf | ProposalDocumentReviewControllerFindOne200OneOfTwo;
