/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ResponseCompanyDto } from './responseCompanyDto';
import type { UserResponseDto } from './userResponseDto';

export interface ProposalInfoResponseDto {
  /** 브랜드사 */
  company: ResponseCompanyDto;
  /** 제안문서 삭제여부 */
  delYn: string;
  /** 사용자ID */
  id: number;
  /** 수정 일시 */
  mdfcnDt: string;
  /** 제안 채널 이름 */
  prpslChnNm: string;
  /** 제안 문서 색상 */
  prpslColorNm: string;
  /** 제안문서 내용 (JSON 값) */
  prpslDocCn: string;
  /** 제안문서 페이지 번호 */
  prpslDocPageNo: number;
  /** 제안문서 상태 (01:임시저장, 02:작성완료) */
  prpslDocSttsCd: string;
  /** 제안 문서 작성일 */
  prpslDocWrtYmd: string;
  /** 제안 문서 폰트 */
  prpslFontNm: string;
  /** 등록 일시 */
  regDt: string;
  /** 등록자 */
  register: UserResponseDto;
}
