/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 답변여부
 * @nullable
 */
export type ProposalDocumentReviewResponseDtoAnsYn = typeof ProposalDocumentReviewResponseDtoAnsYn[keyof typeof ProposalDocumentReviewResponseDtoAnsYn] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalDocumentReviewResponseDtoAnsYn = {
  Y: 'Y',
  N: 'N',
} as const;
