/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface ProposalLogResponseDto {
  /** The unique identifier of the proposal log */
  id: number;
  /**
   * The proposal document page number
   * @nullable
   */
  prpslDocPageNo?: number | null;
  /** The proposal document ID */
  prpslId: number;
  /** The registration timestamp */
  regDt: string;
  /** The user ID who created the log */
  userId: number;
}
