/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ResponseProposalSampleDto } from './responseProposalSampleDto';
import type { ProposalSampleControllerFindAll200AllOfMetadata } from './proposalSampleControllerFindAll200AllOfMetadata';

export type ProposalSampleControllerFindAll200AllOf = {
  data?: ResponseProposalSampleDto[];
  metadata?: ProposalSampleControllerFindAll200AllOfMetadata;
};
