/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalSampleControllerFindOne200OneOf } from './proposalSampleControllerFindOne200OneOf';
import type { ProposalSampleControllerFindOne200OneOfTwo } from './proposalSampleControllerFindOne200OneOfTwo';

export type ProposalSampleControllerFindOne200 = ProposalSampleControllerFindOne200OneOf | ProposalSampleControllerFindOne200OneOfTwo;
