/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalDocumentReviewControllerFindAllAnsYn } from './proposalDocumentReviewControllerFindAllAnsYn';

export type ProposalDocumentReviewControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * 신청 제목
 */
aplyTtl?: string;
/**
 * 회사명
 */
coNm?: string;
/**
 * 담당자명
 */
picNm?: string;
/**
 * 답변여부
 */
ansYn?: ProposalDocumentReviewControllerFindAllAnsYn;
};
