/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ProposalInfoControllerCreate200OneOf } from './proposalInfoControllerCreate200OneOf';
import type { ProposalInfoControllerCreate200OneOfTwo } from './proposalInfoControllerCreate200OneOfTwo';

export type ProposalInfoControllerCreate200 = ProposalInfoControllerCreate200OneOf | ProposalInfoControllerCreate200OneOfTwo;
