/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { QuestionsControllerCreatePublic200OneOf } from './questionsControllerCreatePublic200OneOf';
import type { QuestionsControllerCreatePublic200OneOfTwo } from './questionsControllerCreatePublic200OneOfTwo';

export type QuestionsControllerCreatePublic200 = QuestionsControllerCreatePublic200OneOf | QuestionsControllerCreatePublic200OneOfTwo;
