/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ResponseQuestionAnswerDto } from './responseQuestionAnswerDto';
import type { QuestionsControllerFindAll200AllOfMetadata } from './questionsControllerFindAll200AllOfMetadata';

export type QuestionsControllerFindAll200AllOf = {
  data?: ResponseQuestionAnswerDto[];
  metadata?: QuestionsControllerFindAll200AllOfMetadata;
};
