/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type QuestionsControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * 제목 검색
 */
ttl?: string;
/**
 * 내용 검색
 */
cn?: string;
/**
 * 회사명 검색
 */
coNm?: string;
/**
 * 문의유형 검색(01: 1대1문의, 02: 서비스 문의)
 */
qstnTypeCd?: string;
/**
 * 답변여부 검색
 */
ansYn?: string;
};
