/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { QuestionsControllerCreate200OneOf } from './questionsControllerCreate200OneOf';
import type { QuestionsControllerCreate200OneOfTwo } from './questionsControllerCreate200OneOfTwo';

export type QuestionsControllerCreate200 = QuestionsControllerCreate200OneOf | QuestionsControllerCreate200OneOfTwo;
