/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { QuestionsControllerFindOneBy200OneOf } from './questionsControllerFindOneBy200OneOf';
import type { QuestionsControllerFindOneBy200OneOfTwo } from './questionsControllerFindOneBy200OneOfTwo';

export type QuestionsControllerFindOneBy200 = QuestionsControllerFindOneBy200OneOf | QuestionsControllerFindOneBy200OneOfTwo;
