/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface ResponseBlogDto {
  /** Main content of the blog post */
  body: string;
  /** View count or similar metric */
  cnt?: number;
  /** Short description of the blog post */
  description?: string;
  /** Unique identifier for the blog post */
  id: number;
  /** Publication date of the blog post */
  pubDate: string;
  /** URL of the thumbnail image */
  thumbImg?: string;
  /** The title of the blog post */
  title: string;
  /** The URL of the blog post */
  url: string;
}
