/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface ResponseCompanyDto {
  /** Boss name */
  bossName: string;
  /**
   * Business registration certificate file path
   * @nullable
   */
  brCertFilePathVl?: string | null;
  /** Certification status code */
  certSttsCd: string;
  /**
   * Company address
   * @nullable
   */
  coAddr: string | null;
  /**
   * Company description
   * @nullable
   */
  coDescCn?: string | null;
  /**
   * Company image path
   * @nullable
   */
  coImgPathVl?: string | null;
  /** Company name */
  companyName: string;
  /** Company registration number */
  companyNumber: string;
  /**
   * Company telephone number
   * @nullable
   */
  coTelno?: string | null;
  /** Creation date */
  createdAt: string;
  /** Company ID */
  id: number;
  /** Admin check status */
  isAdminChecked: boolean;
  /**
   * Person in charge email
   * @nullable
   */
  picEmail?: string | null;
  /**
   * Person in charge file name
   * @nullable
   */
  picFlNm?: string | null;
  /**
   * Person in charge name
   * @nullable
   */
  picNm?: string | null;
  /**
   * Person in charge telephone number
   * @nullable
   */
  picTelno?: string | null;
}
