/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 결제상태
 */
export type ResponseProductSourcingDtoStlmStts = typeof ResponseProductSourcingDtoStlmStts[keyof typeof ResponseProductSourcingDtoStlmStts];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseProductSourcingDtoStlmStts = {
  NUMBER_01: '01',
  NUMBER_02: '02',
  NUMBER_03: '03',
} as const;
