/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface ResponseProposalSampleDto {
  /** 고유 식별자 */
  id: number;
  /**
   * 페이지번호
   * @maxLength 100
   */
  page: string;
  /**
   * 등록일시
   * @nullable
   */
  regDt: string | null;
  /**
   * 샘플파일경로
   * @maxLength 100
   * @nullable
   */
  smplFilePathVl: string | null;
  /**
   * 제목
   * @maxLength 100
   * @nullable
   */
  ttl: string | null;
}
