/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ResponseQuestionAnswerDtoAnswer } from './responseQuestionAnswerDtoAnswer';
import type { ResponseQuestionAnswerDtoAnsYn } from './responseQuestionAnswerDtoAnsYn';
import type { ResponseQuestionAnswerDtoQstnTypeCd } from './responseQuestionAnswerDtoQstnTypeCd';
import type { UserResponseDto } from './userResponseDto';

export interface ResponseQuestionAnswerDto {
  /**
   * 답변
   * @nullable
   */
  answer?: ResponseQuestionAnswerDtoAnswer;
  /** 답변여부 */
  ansYn: ResponseQuestionAnswerDtoAnsYn;
  /**
   * 첨부파일경로
   * @nullable
   */
  attchFilePathVl?: string | null;
  /**
   * 희망 유통 채널명
   * @nullable
   */
  chnNm?: string | null;
  /**
   * 내용
   * @nullable
   */
  cn: string | null;
  /**
   * 회사명
   * @nullable
   */
  coNm: string | null;
  /** ID */
  id: number;
  /**
   * 수정 일시
   * @nullable
   */
  mdfcnDt?: string | null;
  /**
   * 수정자 ID
   * @nullable
   */
  mdfrId?: number | null;
  /**
   * 이메일
   * @nullable
   */
  picEmail: string | null;
  /**
   * 이름
   * @nullable
   */
  picNm: string | null;
  /**
   * 전화번호
   * @nullable
   */
  picTelno: string | null;
  /** 문의유형(01: 1대1문의, 02: 서비스 문의) */
  qstnTypeCd: ResponseQuestionAnswerDtoQstnTypeCd;
  /**
   * 등록 일시
   * @nullable
   */
  regDt?: string | null;
  /**
   * 등록자 ID
   * @nullable
   */
  rgtrId?: number | null;
  /** 제목 */
  ttl: string;
  /**
   * 상위 ID
   * @nullable
   */
  upId?: number | null;
  /** 사용자 정보 */
  user: UserResponseDto;
  /** 사용자 ID */
  userId: number;
}
