/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface ResponseMediaFileDto {
  /** 이미지 소스 URL, 데이터 저장할 때 사용 */
  imgSrc: string;
  /** 업로드 URL 직접 업로드 할 때 사용 */
  uploadUrl: string;
}
