/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface SignInAuthDto {
  /** The email of the user */
  email: string;
  /**
   * The password of the user
   * @minLength 8
   */
  password: string;
}
