/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SignUpAuthDtoRole } from './signUpAuthDtoRole';

export interface SignUpAuthDto {
  /** The email of the user */
  email: string;
  /**
   * The password of the user, must be at least 8 characters long
   * @minLength 8
   */
  password: string;
  /** 01: 유통사02:사업가09: 관리자 */
  role: SignUpAuthDtoRole;
}
