/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SourcingControllerUpdateStatus200OneOf } from './sourcingControllerUpdateStatus200OneOf';
import type { SourcingControllerUpdateStatus200OneOfTwo } from './sourcingControllerUpdateStatus200OneOfTwo';

export type SourcingControllerUpdateStatus200 = SourcingControllerUpdateStatus200OneOf | SourcingControllerUpdateStatus200OneOfTwo;
