/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SourcingControllerFindOne200OneOf } from './sourcingControllerFindOne200OneOf';
import type { SourcingControllerFindOne200OneOfTwo } from './sourcingControllerFindOne200OneOfTwo';

export type SourcingControllerFindOne200 = SourcingControllerFindOne200OneOf | SourcingControllerFindOne200OneOfTwo;
