/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { ResponseProductSourcingDto } from './responseProductSourcingDto';
import type { SourcingControllerFindAll200AllOfMetadata } from './sourcingControllerFindAll200AllOfMetadata';

export type SourcingControllerFindAll200AllOf = {
  data?: ResponseProductSourcingDto[];
  metadata?: SourcingControllerFindAll200AllOfMetadata;
};
