/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SourcingControllerUpdate200OneOf } from './sourcingControllerUpdate200OneOf';
import type { SourcingControllerUpdate200OneOfTwo } from './sourcingControllerUpdate200OneOfTwo';

export type SourcingControllerUpdate200 = SourcingControllerUpdate200OneOf | SourcingControllerUpdate200OneOfTwo;
