/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SourcingControllerFindAllAplySttsItem } from './sourcingControllerFindAllAplySttsItem';

export type SourcingControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * 신청상태 
 01: 신청완료, 
 02: 상품 맞춤, 
 03: 소싱상품 유통사 발주 
 04: 제안서 검토 제품발주
 */
aplyStts?: SourcingControllerFindAllAplySttsItem[];
};
