/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SourcingControllerCreate200OneOf } from './sourcingControllerCreate200OneOf';
import type { SourcingControllerCreate200OneOfTwo } from './sourcingControllerCreate200OneOfTwo';

export type SourcingControllerCreate200 = SourcingControllerCreate200OneOf | SourcingControllerCreate200OneOfTwo;
