/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export type SourcingControllerUpdateStatusBodyStatus = typeof SourcingControllerUpdateStatusBodyStatus[keyof typeof SourcingControllerUpdateStatusBodyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SourcingControllerUpdateStatusBodyStatus = {
  NUMBER_01: '01',
  NUMBER_02: '02',
  NUMBER_03: '03',
  NUMBER_04: '04',
} as const;
