/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionsControllerFindAllSbscrbSttsCd } from './subscriptionsControllerFindAllSbscrbSttsCd';
import type { SubscriptionsControllerFindAllSbscrbSeCd } from './subscriptionsControllerFindAllSbscrbSeCd';
import type { SubscriptionsControllerFindAllUserSeCd } from './subscriptionsControllerFindAllUserSeCd';

export type SubscriptionsControllerFindAllParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 100
 */
limit?: number;
/**
 * 결제자이메일
 */
pyrEml?: string;
/**
 * 구독상태코드 01: 구독중, 02: 구독해지, 03: 구독취소
 */
sbscrbSttsCd?: SubscriptionsControllerFindAllSbscrbSttsCd;
/**
 * 구독구분코드 일반:01, 정기:02
 */
sbscrbSeCd?: SubscriptionsControllerFindAllSbscrbSeCd;
/**
 * 구독구분코드 BASIC:01, MASTER:02
 */
userSeCd?: SubscriptionsControllerFindAllUserSeCd;
};
