/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionResponseDtoMdfcnDt } from './subscriptionResponseDtoMdfcnDt';
import type { SubscriptionResponseDtoMdfrId } from './subscriptionResponseDtoMdfrId';
import type { SubscriptionResponseDtoPyrEml } from './subscriptionResponseDtoPyrEml';
import type { SubscriptionResponseDtoPyrMblTelno } from './subscriptionResponseDtoPyrMblTelno';
import type { SubscriptionResponseDtoPyrNm } from './subscriptionResponseDtoPyrNm';
import type { SubscriptionResponseDtoRgtrIp } from './subscriptionResponseDtoRgtrIp';
import type { SubscriptionResponseDtoSbscrbRtrcnDt } from './subscriptionResponseDtoSbscrbRtrcnDt';
import type { SubscriptionResponseDtoSbscrbRtrcnRsnCn } from './subscriptionResponseDtoSbscrbRtrcnRsnCn';
import type { SubscriptionResponseDtoSbscrbSeCd } from './subscriptionResponseDtoSbscrbSeCd';
import type { SubscriptionResponseDtoSbscrbSttsCd } from './subscriptionResponseDtoSbscrbSttsCd';
import type { SubscriptionResponseDtoUserSeCd } from './subscriptionResponseDtoUserSeCd';

export interface SubscriptionResponseDto {
  /**
   * 수정일시
   * @nullable
   */
  mdfcnDt?: SubscriptionResponseDtoMdfcnDt;
  /**
   * 수정자ID
   * @nullable
   */
  mdfrId?: SubscriptionResponseDtoMdfrId;
  /**
   * 결제자이메일
   * @maxLength 100
   * @nullable
   */
  pyrEml?: SubscriptionResponseDtoPyrEml;
  /**
   * 결제자휴대폰번호
   * @maxLength 20
   * @nullable
   */
  pyrMblTelno?: SubscriptionResponseDtoPyrMblTelno;
  /**
   * 결제자명
   * @maxLength 20
   * @nullable
   */
  pyrNm?: SubscriptionResponseDtoPyrNm;
  /** 등록일시 */
  regDt: string;
  /**
   * 등록자ID
   * @nullable
   */
  rgtrId?: number | null;
  /**
   * 등록자IP
   * @maxLength 50
   * @nullable
   */
  rgtrIp?: SubscriptionResponseDtoRgtrIp;
  /** 구독시작일 */
  sbscrbBgngYmd: string;
  /** 구독종료일 */
  sbscrbEndYmd: string;
  /**
   * 구독ID
   * @maxLength 20
   */
  sbscrbId: string;
  /**
   * 구독해지일시
   * @nullable
   */
  sbscrbRtrcnDt?: SubscriptionResponseDtoSbscrbRtrcnDt;
  /**
   * 구독해지사유
   * @maxLength 200
   * @nullable
   */
  sbscrbRtrcnRsnCn?: SubscriptionResponseDtoSbscrbRtrcnRsnCn;
  /**
   * 구독 구분 코드
   * @maxLength 2
   */
  sbscrbSeCd: SubscriptionResponseDtoSbscrbSeCd;
  /**
   * 구독 상태 코드
   * @maxLength 2
   */
  sbscrbSttsCd: SubscriptionResponseDtoSbscrbSttsCd;
  /**
   * 결제ID
   * @maxLength 50
   */
  stlmId: string;
  /**
   * 구독 타입 코드
   * @maxLength 2
   */
  userSeCd: SubscriptionResponseDtoUserSeCd;
}
