/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 구독 상태 코드
 * @maxLength 2
 */
export type SubscriptionResponseDtoSbscrbSttsCd = typeof SubscriptionResponseDtoSbscrbSttsCd[keyof typeof SubscriptionResponseDtoSbscrbSttsCd];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionResponseDtoSbscrbSttsCd = {
  NUMBER_01: '01',
  NUMBER_02: '02',
  NUMBER_03: '03',
} as const;
