/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionsControllerCancel200OneOf } from './subscriptionsControllerCancel200OneOf';
import type { SubscriptionsControllerCancel200OneOfTwo } from './subscriptionsControllerCancel200OneOfTwo';

export type SubscriptionsControllerCancel200 = SubscriptionsControllerCancel200OneOf | SubscriptionsControllerCancel200OneOfTwo;
