/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 구독 타입 코드
 * @maxLength 2
 */
export type SubscriptionResponseDtoUserSeCd = typeof SubscriptionResponseDtoUserSeCd[keyof typeof SubscriptionResponseDtoUserSeCd];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionResponseDtoUserSeCd = {
  NUMBER_01: '01',
  NUMBER_02: '02',
} as const;
