/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionsControllerUpdate200OneOf } from './subscriptionsControllerUpdate200OneOf';
import type { SubscriptionsControllerUpdate200OneOfTwo } from './subscriptionsControllerUpdate200OneOfTwo';

export type SubscriptionsControllerUpdate200 = SubscriptionsControllerUpdate200OneOf | SubscriptionsControllerUpdate200OneOfTwo;
