/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 결제자명
 * @maxLength 20
 * @nullable
 */
export type SubscriptionResponseDtoPyrNm = { [key: string]: unknown } | null;
