/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionResponseDto } from './subscriptionResponseDto';
import type { SubscriptionsControllerFindAll200AllOfMetadata } from './subscriptionsControllerFindAll200AllOfMetadata';

export type SubscriptionsControllerFindAll200AllOf = {
  data?: SubscriptionResponseDto[];
  metadata?: SubscriptionsControllerFindAll200AllOfMetadata;
};
