/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 결제자휴대폰번호
 * @maxLength 20
 * @nullable
 */
export type SubscriptionResponseDtoPyrMblTelno = { [key: string]: unknown } | null;
