/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 결제자이메일
 * @maxLength 100
 * @nullable
 */
export type SubscriptionResponseDtoPyrEml = { [key: string]: unknown } | null;
