/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionsControllerCreate200OneOf } from './subscriptionsControllerCreate200OneOf';
import type { SubscriptionsControllerCreate200OneOfTwo } from './subscriptionsControllerCreate200OneOfTwo';

export type SubscriptionsControllerCreate200 = SubscriptionsControllerCreate200OneOf | SubscriptionsControllerCreate200OneOfTwo;
