/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 구독해지사유
 * @maxLength 200
 * @nullable
 */
export type SubscriptionResponseDtoSbscrbRtrcnRsnCn = { [key: string]: unknown } | null;
