/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface UpdateEducationDto {
  /** 종료일 */
  endDate?: string;
  /**
   * 이미지 URL
   * @maxLength 100
   */
  image?: string;
  /** 관리자 선택 여부 */
  isAdminPick?: boolean;
  /**
   * 장소
   * @maxLength 200
   */
  place?: string;
  /** 가격 */
  price?: number;
  /** 시작일 */
  startDate?: string;
  /**
   * 대상
   * @maxLength 200
   */
  target?: string;
  /**
   * 교육 제목
   * @maxLength 300
   */
  title?: string;
}
