/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { UpdateProductSourcingDtoAplyCn } from './updateProductSourcingDtoAplyCn';
import type { UpdateProductSourcingDtoAplyStts } from './updateProductSourcingDtoAplyStts';

export interface UpdateProductSourcingDto {
  /** 신청내용 */
  aplyCn?: UpdateProductSourcingDtoAplyCn;
  /** 의뢰신청명 */
  aplymNm?: string;
  /** 신청상태 */
  aplyStts?: UpdateProductSourcingDtoAplyStts;
  /** 상품 분류값 */
  prdctClsfVl?: string;
}
