/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { UpdateProposalDocumentReviewDtoAnsYn } from './updateProposalDocumentReviewDtoAnsYn';

export interface UpdateProposalDocumentReviewDto {
  /** 답변내용 */
  ansCn?: string;
  /** 답변여부 */
  ansYn: UpdateProposalDocumentReviewDtoAnsYn;
}
