/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 답변여부
 */
export type UpdateProposalDocumentReviewDtoAnsYn = typeof UpdateProposalDocumentReviewDtoAnsYn[keyof typeof UpdateProposalDocumentReviewDtoAnsYn];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProposalDocumentReviewDtoAnsYn = {
  Y: 'Y',
  N: 'N',
} as const;
