/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface UpdateCategoryDto {
  /**
   * 코드
   * @maxLength 20
   */
  cd?: string;
  /**
   * 코드 분류명
   * @maxLength 100
   */
  cdClsfNm?: string;
  /**
   * 코드 레벨
   * @maxLength 20
   */
  cdLvl?: number;
  /**
   * 코드명
   * @maxLength 100
   */
  cdNm?: string;
  /**
   * 코드 전체명
   * @maxLength 200
   */
  cdWholNm?: string;
}
