/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface UpdateSubscriptionDto {
  /**
   * 결제자이메일
   * @maxLength 100
   */
  pyrEml?: string;
  /**
   * 결제자휴대폰번호
   * @maxLength 20
   */
  pyrMblTelno?: string;
  /**
   * 결제자명
   * @maxLength 20
   */
  pyrNm?: string;
  /** 구독시작일 */
  sbscrbBgngYmd?: string;
  /** 구독종료일 */
  sbscrbEndYmd?: string;
  /** 구독해지일시 */
  sbscrbRtrcnDt?: string;
  /**
   * 구독해지사유
   * @maxLength 200
   */
  sbscrbRtrcnRsnCn?: string;
  /**
   * 구독구분코드
   * @maxLength 2
   */
  sbscrbSeCd?: string;
  /**
   * 구독상태코드
   * @maxLength 2
   */
  sbscrbSttsCd?: string;
  /**
   * 사용자구분코드
   * @maxLength 2
   */
  userSeCd?: string;
}
