/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */
import type { UpdateMultipleProductStatusDtoPrdctSttsCd } from './updateMultipleProductStatusDtoPrdctSttsCd';

export interface UpdateMultipleProductStatusDto {
  /** 상태를 변경할 상품 ID 목록 */
  prdctIds: number[];
  /** 새로운 상품 상태 코드 */
  prdctSttsCd: UpdateMultipleProductStatusDtoPrdctSttsCd;
}
