/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

/**
 * 상품 상태 코드
 */
export type UpdateProductDtoPrdctSttsCd = typeof UpdateProductDtoPrdctSttsCd[keyof typeof UpdateProductDtoPrdctSttsCd];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProductDtoPrdctSttsCd = {
  NUMBER_01: '01',
  NUMBER_02: '02',
  NUMBER_03: '03',
} as const;
