/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface UserResponseDto {
  /** 이메일 주소 */
  email: string;
  /** 사용자 ID */
  id: number;
  /** 활성화 여부 */
  isActive: boolean;
  /** 관리자 여부 */
  isAdmin: boolean;
  /** 슈퍼유저 여부 */
  isSuperuser: boolean;
  /** 가입일 */
  joinDate: string;
  /**
   * 마지막 로그인 일시
   * @nullable
   */
  lastLogin: string | null;
  /** 사용자 유형 코드 */
  mbrSeCd: string;
}
