/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * View Nest API
 * API documentation for View Nest application
 * OpenAPI spec version: 1.0
 */

export interface VerifyCodeDto {
  /** 인증 코드 */
  code: string;
  /** 이메일 */
  email: string;
}
